#!/bin/bash

export GOPATH=$(pwd)

set -ex
go build bytehisto
go build cat
go build csum
go build echo
go build hello
go build hex
go build millis2gmt
go build nowmillis
go build stamplines
go build wc
